package com.example.demo.dao;

import com.example.demo.model.Person;

import java.util.UUID;

public interface PersonDao {
    int insertPerson(UUID id, Person person);// Here  we have the id, with id= null and person name

    default int addPerson(Person person){
        UUID id = UUID.randomUUID();
        return  insertPerson(id, person); // id is the random UUID generated by addPerson()., with the person.getName
    }
}